/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMarketplace } from "./IMarketplace";
export type { IRental } from "./IRental";
export type { RittyStakingPool } from "./RittyStakingPool";
