/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RittyStakingPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimAllRewards"
      | "claimReward"
      | "createPool"
      | "creatorFeeBps"
      | "distributeRevenue"
      | "getAPY"
      | "getAllPools"
      | "getPoolInfo"
      | "marketplace"
      | "owner"
      | "pendingCreatorFees"
      | "pendingPlatformFees"
      | "pendingReward"
      | "platformFeeBps"
      | "poolAgentIds"
      | "pools"
      | "stake"
      | "stakerFeeBps"
      | "stakerShare"
      | "stakers"
      | "transferOwnership"
      | "unstake"
      | "updateFees"
      | "withdrawCreatorFee"
      | "withdrawPlatformFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesUpdated"
      | "PoolCreated"
      | "RevenueDistributed"
      | "RewardClaimed"
      | "Staked"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimAllRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeRevenue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAPY",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplace",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingCreatorFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingPlatformFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingReward",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolAgentIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pools", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "stakerFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakerShare",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakers",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFees",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCreatorFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFee",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimAllRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creatorFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAPY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingCreatorFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingPlatformFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolAgentIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakerFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCreatorFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFee",
    data: BytesLike
  ): Result;
}

export namespace FeesUpdatedEvent {
  export type InputTuple = [
    stakerFee: BigNumberish,
    creatorFee: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    stakerFee: bigint,
    creatorFee: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    stakerFee: bigint;
    creatorFee: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueDistributedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    totalAmount: BigNumberish,
    stakerShare: BigNumberish,
    creatorShare: BigNumberish,
    platformShare: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    totalAmount: bigint,
    stakerShare: bigint,
    creatorShare: bigint,
    platformShare: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    totalAmount: bigint;
    stakerShare: bigint;
    creatorShare: bigint;
    platformShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    staker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [agentId: bigint, staker: string, amount: bigint];
  export interface OutputObject {
    agentId: bigint;
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    staker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [agentId: bigint, staker: string, amount: bigint];
  export interface OutputObject {
    agentId: bigint;
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    staker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [agentId: bigint, staker: string, amount: bigint];
  export interface OutputObject {
    agentId: bigint;
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RittyStakingPool extends BaseContract {
  connect(runner?: ContractRunner | null): RittyStakingPool;
  waitForDeployment(): Promise<this>;

  interface: RittyStakingPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimAllRewards: TypedContractMethod<[], [void], "nonpayable">;

  claimReward: TypedContractMethod<
    [_agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPool: TypedContractMethod<
    [_agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  creatorFeeBps: TypedContractMethod<[], [bigint], "view">;

  distributeRevenue: TypedContractMethod<
    [_agentId: BigNumberish],
    [void],
    "payable"
  >;

  getAPY: TypedContractMethod<[_agentId: BigNumberish], [bigint], "view">;

  getAllPools: TypedContractMethod<[], [bigint[]], "view">;

  getPoolInfo: TypedContractMethod<
    [_agentId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        totalStaked: bigint;
        totalRewards: bigint;
        stakerCount: bigint;
        apy: bigint;
      }
    ],
    "view"
  >;

  marketplace: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingCreatorFees: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  pendingPlatformFees: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  pendingReward: TypedContractMethod<
    [_agentId: BigNumberish, _staker: AddressLike],
    [bigint],
    "view"
  >;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  poolAgentIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  pools: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalStaked: bigint;
        rewardPerToken: bigint;
        lastUpdateTime: bigint;
        totalRewards: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  stake: TypedContractMethod<[_agentId: BigNumberish], [void], "payable">;

  stakerFeeBps: TypedContractMethod<[], [bigint], "view">;

  stakerShare: TypedContractMethod<
    [_agentId: BigNumberish, _staker: AddressLike],
    [bigint],
    "view"
  >;

  stakers: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        staked: bigint;
        rewardPerTokenPaid: bigint;
        rewards: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<
    [_agentId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateFees: TypedContractMethod<
    [
      _stakerFee: BigNumberish,
      _creatorFee: BigNumberish,
      _platformFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdrawCreatorFee: TypedContractMethod<
    [_agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawPlatformFee: TypedContractMethod<
    [_agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimAllRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[_agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<[_agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "creatorFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributeRevenue"
  ): TypedContractMethod<[_agentId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getAPY"
  ): TypedContractMethod<[_agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllPools"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [_agentId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        totalStaked: bigint;
        totalRewards: bigint;
        stakerCount: bigint;
        apy: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingCreatorFees"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingPlatformFees"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingReward"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _staker: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "poolAgentIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalStaked: bigint;
        rewardPerToken: bigint;
        lastUpdateTime: bigint;
        totalRewards: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[_agentId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "stakerFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakerShare"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _staker: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        staked: bigint;
        rewardPerTokenPaid: bigint;
        rewards: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateFees"
  ): TypedContractMethod<
    [
      _stakerFee: BigNumberish,
      _creatorFee: BigNumberish,
      _platformFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawCreatorFee"
  ): TypedContractMethod<[_agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPlatformFee"
  ): TypedContractMethod<[_agentId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "FeesUpdated"
  ): TypedContractEvent<
    FeesUpdatedEvent.InputTuple,
    FeesUpdatedEvent.OutputTuple,
    FeesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RevenueDistributed"
  ): TypedContractEvent<
    RevenueDistributedEvent.InputTuple,
    RevenueDistributedEvent.OutputTuple,
    RevenueDistributedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "FeesUpdated(uint256,uint256,uint256)": TypedContractEvent<
      FeesUpdatedEvent.InputTuple,
      FeesUpdatedEvent.OutputTuple,
      FeesUpdatedEvent.OutputObject
    >;
    FeesUpdated: TypedContractEvent<
      FeesUpdatedEvent.InputTuple,
      FeesUpdatedEvent.OutputTuple,
      FeesUpdatedEvent.OutputObject
    >;

    "PoolCreated(uint256)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;

    "RevenueDistributed(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RevenueDistributedEvent.InputTuple,
      RevenueDistributedEvent.OutputTuple,
      RevenueDistributedEvent.OutputObject
    >;
    RevenueDistributed: TypedContractEvent<
      RevenueDistributedEvent.InputTuple,
      RevenueDistributedEvent.OutputTuple,
      RevenueDistributedEvent.OutputObject
    >;

    "RewardClaimed(uint256,address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "Staked(uint256,address,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unstaked(uint256,address,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
