/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRental,
  IRentalInterface,
} from "../../RittyStakingPool.sol/IRental";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "agents",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "description",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "pricePerHour",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalEarnings",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalRentals",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rating",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "ratingCount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isActive",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRental__factory {
  static readonly abi = _abi;
  static createInterface(): IRentalInterface {
    return new Interface(_abi) as IRentalInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRental {
    return new Contract(address, _abi, runner) as unknown as IRental;
  }
}
