/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStakingPool__factory } from "./IStakingPool__factory";
export { RittyRental__factory } from "./RittyRental__factory";
