/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStakingPool,
  IStakingPoolInterface,
} from "../../RittyRental.sol/IStakingPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
    ],
    name: "distributeRevenue",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IStakingPool__factory {
  static readonly abi = _abi;
  static createInterface(): IStakingPoolInterface {
    return new Interface(_abi) as IStakingPoolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStakingPool {
    return new Contract(address, _abi, runner) as unknown as IStakingPool;
  }
}
