/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace RittyRental {
  export type RentalStruct = {
    renter: AddressLike;
    agentId: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    totalPaid: BigNumberish;
    isActive: boolean;
  };

  export type RentalStructOutput = [
    renter: string,
    agentId: bigint,
    startTime: bigint,
    endTime: bigint,
    totalPaid: bigint,
    isActive: boolean
  ] & {
    renter: string;
    agentId: bigint;
    startTime: bigint;
    endTime: bigint;
    totalPaid: bigint;
    isActive: boolean;
  };
}

export interface RittyRentalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentCount"
      | "agents"
      | "calculateRentalCost"
      | "deactivateAgent"
      | "getActiveAgents"
      | "getAgent"
      | "getRentals"
      | "getUserAgents"
      | "hasRated"
      | "listAgent"
      | "owner"
      | "rateAgent"
      | "reactivateAgent"
      | "rentAgent"
      | "rentals"
      | "stakingPool"
      | "transferOwnership"
      | "updatePrice"
      | "updateStakingPool"
      | "userAgents"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentListed"
      | "AgentRated"
      | "AgentReactivated"
      | "AgentRented"
      | "PriceUpdated"
      | "StakingPoolUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRentalCost",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveAgents",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRentals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRated",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listAgent",
    values: [string, string, string[], BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rateAgent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rentAgent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rentals",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStakingPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userAgents",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "agentCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateRentalCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRentals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRated", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rateAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rentAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rentals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStakingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userAgents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentListedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    name: string
  ];
  export type OutputTuple = [agentId: bigint, owner: string, name: string];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    rater: AddressLike,
    rating: BigNumberish
  ];
  export type OutputTuple = [agentId: bigint, rater: string, rating: bigint];
  export interface OutputObject {
    agentId: bigint;
    rater: string;
    rating: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentReactivatedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRentedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    renter: AddressLike,
    duration: BigNumberish,
    totalPaid: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    renter: string,
    duration: bigint,
    totalPaid: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    renter: string;
    duration: bigint;
    totalPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    oldPrice: BigNumberish,
    newPrice: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    oldPrice: bigint,
    newPrice: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakingPoolUpdatedEvent {
  export type InputTuple = [oldPool: AddressLike, newPool: AddressLike];
  export type OutputTuple = [oldPool: string, newPool: string];
  export interface OutputObject {
    oldPool: string;
    newPool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RittyRental extends BaseContract {
  connect(runner?: ContractRunner | null): RittyRental;
  waitForDeployment(): Promise<this>;

  interface: RittyRentalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentCount: TypedContractMethod<[], [bigint], "view">;

  agents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        owner: string;
        name: string;
        description: string;
        pricePerHour: bigint;
        totalEarnings: bigint;
        totalRentals: bigint;
        rating: bigint;
        ratingCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  calculateRentalCost: TypedContractMethod<
    [_agentId: BigNumberish, _hours: BigNumberish],
    [bigint],
    "view"
  >;

  deactivateAgent: TypedContractMethod<
    [_agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveAgents: TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [bigint[]],
    "view"
  >;

  getAgent: TypedContractMethod<
    [_agentId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        ownerAddr: string;
        name: string;
        description: string;
        pricePerHour: bigint;
        totalEarnings: bigint;
        totalRentals: bigint;
        rating: bigint;
        ratingCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getRentals: TypedContractMethod<
    [_agentId: BigNumberish],
    [RittyRental.RentalStructOutput[]],
    "view"
  >;

  getUserAgents: TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;

  hasRated: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  listAgent: TypedContractMethod<
    [
      _name: string,
      _description: string,
      _capabilities: string[],
      _pricePerHour: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  rateAgent: TypedContractMethod<
    [_agentId: BigNumberish, _rating: BigNumberish],
    [void],
    "nonpayable"
  >;

  reactivateAgent: TypedContractMethod<
    [_agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rentAgent: TypedContractMethod<
    [_agentId: BigNumberish, _hours: BigNumberish],
    [void],
    "payable"
  >;

  rentals: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        renter: string;
        agentId: bigint;
        startTime: bigint;
        endTime: bigint;
        totalPaid: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  stakingPool: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePrice: TypedContractMethod<
    [_agentId: BigNumberish, _newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateStakingPool: TypedContractMethod<
    [_newPool: AddressLike],
    [void],
    "nonpayable"
  >;

  userAgents: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawPlatformFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        owner: string;
        name: string;
        description: string;
        pricePerHour: bigint;
        totalEarnings: bigint;
        totalRentals: bigint;
        rating: bigint;
        ratingCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateRentalCost"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _hours: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateAgent"
  ): TypedContractMethod<[_agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveAgents"
  ): TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [_agentId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        ownerAddr: string;
        name: string;
        description: string;
        pricePerHour: bigint;
        totalEarnings: bigint;
        totalRentals: bigint;
        rating: bigint;
        ratingCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRentals"
  ): TypedContractMethod<
    [_agentId: BigNumberish],
    [RittyRental.RentalStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserAgents"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasRated"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "listAgent"
  ): TypedContractMethod<
    [
      _name: string,
      _description: string,
      _capabilities: string[],
      _pricePerHour: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rateAgent"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _rating: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reactivateAgent"
  ): TypedContractMethod<[_agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rentAgent"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _hours: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "rentals"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        renter: string;
        agentId: bigint;
        startTime: bigint;
        endTime: bigint;
        totalPaid: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakingPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePrice"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateStakingPool"
  ): TypedContractMethod<[_newPool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userAgents"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentListed"
  ): TypedContractEvent<
    AgentListedEvent.InputTuple,
    AgentListedEvent.OutputTuple,
    AgentListedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRated"
  ): TypedContractEvent<
    AgentRatedEvent.InputTuple,
    AgentRatedEvent.OutputTuple,
    AgentRatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentReactivated"
  ): TypedContractEvent<
    AgentReactivatedEvent.InputTuple,
    AgentReactivatedEvent.OutputTuple,
    AgentReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRented"
  ): TypedContractEvent<
    AgentRentedEvent.InputTuple,
    AgentRentedEvent.OutputTuple,
    AgentRentedEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StakingPoolUpdated"
  ): TypedContractEvent<
    StakingPoolUpdatedEvent.InputTuple,
    StakingPoolUpdatedEvent.OutputTuple,
    StakingPoolUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(uint256)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentListed(uint256,address,string)": TypedContractEvent<
      AgentListedEvent.InputTuple,
      AgentListedEvent.OutputTuple,
      AgentListedEvent.OutputObject
    >;
    AgentListed: TypedContractEvent<
      AgentListedEvent.InputTuple,
      AgentListedEvent.OutputTuple,
      AgentListedEvent.OutputObject
    >;

    "AgentRated(uint256,address,uint8)": TypedContractEvent<
      AgentRatedEvent.InputTuple,
      AgentRatedEvent.OutputTuple,
      AgentRatedEvent.OutputObject
    >;
    AgentRated: TypedContractEvent<
      AgentRatedEvent.InputTuple,
      AgentRatedEvent.OutputTuple,
      AgentRatedEvent.OutputObject
    >;

    "AgentReactivated(uint256)": TypedContractEvent<
      AgentReactivatedEvent.InputTuple,
      AgentReactivatedEvent.OutputTuple,
      AgentReactivatedEvent.OutputObject
    >;
    AgentReactivated: TypedContractEvent<
      AgentReactivatedEvent.InputTuple,
      AgentReactivatedEvent.OutputTuple,
      AgentReactivatedEvent.OutputObject
    >;

    "AgentRented(uint256,address,uint256,uint256)": TypedContractEvent<
      AgentRentedEvent.InputTuple,
      AgentRentedEvent.OutputTuple,
      AgentRentedEvent.OutputObject
    >;
    AgentRented: TypedContractEvent<
      AgentRentedEvent.InputTuple,
      AgentRentedEvent.OutputTuple,
      AgentRentedEvent.OutputObject
    >;

    "PriceUpdated(uint256,uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "StakingPoolUpdated(address,address)": TypedContractEvent<
      StakingPoolUpdatedEvent.InputTuple,
      StakingPoolUpdatedEvent.OutputTuple,
      StakingPoolUpdatedEvent.OutputObject
    >;
    StakingPoolUpdated: TypedContractEvent<
      StakingPoolUpdatedEvent.InputTuple,
      StakingPoolUpdatedEvent.OutputTuple,
      StakingPoolUpdatedEvent.OutputObject
    >;
  };
}
