/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPersistentAgent } from "./IPersistentAgent";
export type { ISovereignAgent } from "./ISovereignAgent";
