/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IPersistentAgentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "executeTask"
      | "isRunning"
      | "owner"
      | "pause"
      | "readMemory"
      | "resume"
      | "updateMemory"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentPaused"
      | "AgentResumed"
      | "MemoryUpdated"
      | "TaskExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "executeTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isRunning", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "readMemory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "resume", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateMemory",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isRunning", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "readMemory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resume", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateMemory",
    data: BytesLike
  ): Result;
}

export namespace AgentPausedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentResumedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemoryUpdatedEvent {
  export type InputTuple = [key: BytesLike, value: BytesLike];
  export type OutputTuple = [key: string, value: string];
  export interface OutputObject {
    key: string;
    value: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskExecutedEvent {
  export type InputTuple = [taskId: BytesLike, result: BytesLike];
  export type OutputTuple = [taskId: string, result: string];
  export interface OutputObject {
    taskId: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPersistentAgent extends BaseContract {
  connect(runner?: ContractRunner | null): IPersistentAgent;
  waitForDeployment(): Promise<this>;

  interface: IPersistentAgentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeTask: TypedContractMethod<[_task: BytesLike], [string], "nonpayable">;

  isRunning: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  readMemory: TypedContractMethod<[_key: BytesLike], [string], "view">;

  resume: TypedContractMethod<[], [void], "nonpayable">;

  updateMemory: TypedContractMethod<
    [_key: BytesLike, _value: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeTask"
  ): TypedContractMethod<[_task: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "isRunning"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "readMemory"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "resume"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMemory"
  ): TypedContractMethod<
    [_key: BytesLike, _value: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentPaused"
  ): TypedContractEvent<
    AgentPausedEvent.InputTuple,
    AgentPausedEvent.OutputTuple,
    AgentPausedEvent.OutputObject
  >;
  getEvent(
    key: "AgentResumed"
  ): TypedContractEvent<
    AgentResumedEvent.InputTuple,
    AgentResumedEvent.OutputTuple,
    AgentResumedEvent.OutputObject
  >;
  getEvent(
    key: "MemoryUpdated"
  ): TypedContractEvent<
    MemoryUpdatedEvent.InputTuple,
    MemoryUpdatedEvent.OutputTuple,
    MemoryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskExecuted"
  ): TypedContractEvent<
    TaskExecutedEvent.InputTuple,
    TaskExecutedEvent.OutputTuple,
    TaskExecutedEvent.OutputObject
  >;

  filters: {
    "AgentPaused()": TypedContractEvent<
      AgentPausedEvent.InputTuple,
      AgentPausedEvent.OutputTuple,
      AgentPausedEvent.OutputObject
    >;
    AgentPaused: TypedContractEvent<
      AgentPausedEvent.InputTuple,
      AgentPausedEvent.OutputTuple,
      AgentPausedEvent.OutputObject
    >;

    "AgentResumed()": TypedContractEvent<
      AgentResumedEvent.InputTuple,
      AgentResumedEvent.OutputTuple,
      AgentResumedEvent.OutputObject
    >;
    AgentResumed: TypedContractEvent<
      AgentResumedEvent.InputTuple,
      AgentResumedEvent.OutputTuple,
      AgentResumedEvent.OutputObject
    >;

    "MemoryUpdated(bytes32,bytes)": TypedContractEvent<
      MemoryUpdatedEvent.InputTuple,
      MemoryUpdatedEvent.OutputTuple,
      MemoryUpdatedEvent.OutputObject
    >;
    MemoryUpdated: TypedContractEvent<
      MemoryUpdatedEvent.InputTuple,
      MemoryUpdatedEvent.OutputTuple,
      MemoryUpdatedEvent.OutputObject
    >;

    "TaskExecuted(bytes32,bytes)": TypedContractEvent<
      TaskExecutedEvent.InputTuple,
      TaskExecutedEvent.OutputTuple,
      TaskExecutedEvent.OutputObject
    >;
    TaskExecuted: TypedContractEvent<
      TaskExecutedEvent.InputTuple,
      TaskExecutedEvent.OutputTuple,
      TaskExecutedEvent.OutputObject
    >;
  };
}
