/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ISovereignAgentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelTask"
      | "createTask"
      | "getTaskResult"
      | "getTaskStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TaskCompleted" | "TaskCreated" | "TaskFailed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskResult",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskStatus",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaskResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTaskStatus",
    data: BytesLike
  ): Result;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [taskId: BytesLike, output: BytesLike];
  export type OutputTuple = [taskId: string, output: string];
  export interface OutputObject {
    taskId: string;
    output: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [taskId: BytesLike, input: BytesLike];
  export type OutputTuple = [taskId: string, input: string];
  export interface OutputObject {
    taskId: string;
    input: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskFailedEvent {
  export type InputTuple = [taskId: BytesLike, reason: string];
  export type OutputTuple = [taskId: string, reason: string];
  export interface OutputObject {
    taskId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISovereignAgent extends BaseContract {
  connect(runner?: ContractRunner | null): ISovereignAgent;
  waitForDeployment(): Promise<this>;

  interface: ISovereignAgentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelTask: TypedContractMethod<[_taskId: BytesLike], [void], "nonpayable">;

  createTask: TypedContractMethod<[_input: BytesLike], [string], "nonpayable">;

  getTaskResult: TypedContractMethod<[_taskId: BytesLike], [string], "view">;

  getTaskStatus: TypedContractMethod<[_taskId: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[_taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<[_input: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getTaskResult"
  ): TypedContractMethod<[_taskId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTaskStatus"
  ): TypedContractMethod<[_taskId: BytesLike], [bigint], "view">;

  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskFailed"
  ): TypedContractEvent<
    TaskFailedEvent.InputTuple,
    TaskFailedEvent.OutputTuple,
    TaskFailedEvent.OutputObject
  >;

  filters: {
    "TaskCompleted(bytes32,bytes)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskCreated(bytes32,bytes)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskFailed(bytes32,string)": TypedContractEvent<
      TaskFailedEvent.InputTuple,
      TaskFailedEvent.OutputTuple,
      TaskFailedEvent.OutputObject
    >;
    TaskFailed: TypedContractEvent<
      TaskFailedEvent.InputTuple,
      TaskFailedEvent.OutputTuple,
      TaskFailedEvent.OutputObject
    >;
  };
}
