/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentMarketplace {
  export type RentalStruct = {
    renter: AddressLike;
    agentId: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    totalPaid: BigNumberish;
    isActive: boolean;
  };

  export type RentalStructOutput = [
    renter: string,
    agentId: bigint,
    startTime: bigint,
    endTime: bigint,
    totalPaid: bigint,
    isActive: boolean
  ] & {
    renter: string;
    agentId: bigint;
    startTime: bigint;
    endTime: bigint;
    totalPaid: bigint;
    isActive: boolean;
  };
}

export interface AgentMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "PLATFORM_FEE_BPS"
      | "agentCount"
      | "agents"
      | "calculateRentalCost"
      | "createSovereignTask"
      | "deactivateAgent"
      | "executeTask"
      | "getActiveAgents"
      | "getAgent"
      | "getRentals"
      | "getUserAgents"
      | "hasRated"
      | "isPrecompileAgent"
      | "listAgent"
      | "platformTreasury"
      | "rateAgent"
      | "reactivateAgent"
      | "rentAgent"
      | "rentals"
      | "userAgents"
      | "withdrawEarnings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentListed"
      | "AgentRated"
      | "AgentRented"
      | "EarningsWithdrawn"
      | "TaskExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRentalCost",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSovereignTask",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTask",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveAgents",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRentals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRated",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPrecompileAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listAgent",
    values: [AddressLike, string, string, string[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rateAgent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rentAgent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rentals",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userAgents",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEarnings",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateRentalCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSovereignTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRentals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRated", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPrecompileAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rateAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rentAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rentals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userAgents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEarnings",
    data: BytesLike
  ): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentListedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    name: string,
    agentType: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    owner: string,
    name: string,
    agentType: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    name: string;
    agentType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    rater: AddressLike,
    rating: BigNumberish
  ];
  export type OutputTuple = [agentId: bigint, rater: string, rating: bigint];
  export interface OutputObject {
    agentId: bigint;
    rater: string;
    rating: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRentedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    renter: AddressLike,
    duration: BigNumberish,
    totalPaid: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    renter: string,
    duration: bigint,
    totalPaid: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    renter: string;
    duration: bigint;
    totalPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarningsWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskExecutedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    taskId: BytesLike,
    renter: AddressLike
  ];
  export type OutputTuple = [agentId: bigint, taskId: string, renter: string];
  export interface OutputObject {
    agentId: bigint;
    taskId: string;
    renter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): AgentMarketplace;
  waitForDeployment(): Promise<this>;

  interface: AgentMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  agentCount: TypedContractMethod<[], [bigint], "view">;

  agents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        owner: string;
        agentContract: string;
        name: string;
        description: string;
        pricePerHour: bigint;
        totalEarnings: bigint;
        totalRentals: bigint;
        rating: bigint;
        ratingCount: bigint;
        isActive: boolean;
        agentType: bigint;
      }
    ],
    "view"
  >;

  calculateRentalCost: TypedContractMethod<
    [_agentId: BigNumberish, _hours: BigNumberish],
    [bigint],
    "view"
  >;

  createSovereignTask: TypedContractMethod<
    [_agentId: BigNumberish, _input: BytesLike],
    [string],
    "nonpayable"
  >;

  deactivateAgent: TypedContractMethod<
    [_agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeTask: TypedContractMethod<
    [_agentId: BigNumberish, _task: BytesLike],
    [string],
    "nonpayable"
  >;

  getActiveAgents: TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [bigint[]],
    "view"
  >;

  getAgent: TypedContractMethod<
    [_agentId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        owner: string;
        agentContract: string;
        name: string;
        description: string;
        pricePerHour: bigint;
        totalEarnings: bigint;
        totalRentals: bigint;
        rating: bigint;
        ratingCount: bigint;
        isActive: boolean;
        agentType: bigint;
      }
    ],
    "view"
  >;

  getRentals: TypedContractMethod<
    [_agentId: BigNumberish],
    [AgentMarketplace.RentalStructOutput[]],
    "view"
  >;

  getUserAgents: TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;

  hasRated: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isPrecompileAgent: TypedContractMethod<
    [_agentId: BigNumberish],
    [boolean],
    "view"
  >;

  listAgent: TypedContractMethod<
    [
      _agentContract: AddressLike,
      _name: string,
      _description: string,
      _capabilities: string[],
      _pricePerHour: BigNumberish,
      _agentType: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  rateAgent: TypedContractMethod<
    [_agentId: BigNumberish, _rating: BigNumberish],
    [void],
    "nonpayable"
  >;

  reactivateAgent: TypedContractMethod<
    [_agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rentAgent: TypedContractMethod<
    [_agentId: BigNumberish, _hours: BigNumberish],
    [void],
    "payable"
  >;

  rentals: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        renter: string;
        agentId: bigint;
        startTime: bigint;
        endTime: bigint;
        totalPaid: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  userAgents: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawEarnings: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        owner: string;
        agentContract: string;
        name: string;
        description: string;
        pricePerHour: bigint;
        totalEarnings: bigint;
        totalRentals: bigint;
        rating: bigint;
        ratingCount: bigint;
        isActive: boolean;
        agentType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateRentalCost"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _hours: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createSovereignTask"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _input: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateAgent"
  ): TypedContractMethod<[_agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTask"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _task: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveAgents"
  ): TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [_agentId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        owner: string;
        agentContract: string;
        name: string;
        description: string;
        pricePerHour: bigint;
        totalEarnings: bigint;
        totalRentals: bigint;
        rating: bigint;
        ratingCount: bigint;
        isActive: boolean;
        agentType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRentals"
  ): TypedContractMethod<
    [_agentId: BigNumberish],
    [AgentMarketplace.RentalStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserAgents"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasRated"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPrecompileAgent"
  ): TypedContractMethod<[_agentId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "listAgent"
  ): TypedContractMethod<
    [
      _agentContract: AddressLike,
      _name: string,
      _description: string,
      _capabilities: string[],
      _pricePerHour: BigNumberish,
      _agentType: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rateAgent"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _rating: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reactivateAgent"
  ): TypedContractMethod<[_agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rentAgent"
  ): TypedContractMethod<
    [_agentId: BigNumberish, _hours: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "rentals"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        renter: string;
        agentId: bigint;
        startTime: bigint;
        endTime: bigint;
        totalPaid: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userAgents"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawEarnings"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentListed"
  ): TypedContractEvent<
    AgentListedEvent.InputTuple,
    AgentListedEvent.OutputTuple,
    AgentListedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRated"
  ): TypedContractEvent<
    AgentRatedEvent.InputTuple,
    AgentRatedEvent.OutputTuple,
    AgentRatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRented"
  ): TypedContractEvent<
    AgentRentedEvent.InputTuple,
    AgentRentedEvent.OutputTuple,
    AgentRentedEvent.OutputObject
  >;
  getEvent(
    key: "EarningsWithdrawn"
  ): TypedContractEvent<
    EarningsWithdrawnEvent.InputTuple,
    EarningsWithdrawnEvent.OutputTuple,
    EarningsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "TaskExecuted"
  ): TypedContractEvent<
    TaskExecutedEvent.InputTuple,
    TaskExecutedEvent.OutputTuple,
    TaskExecutedEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(uint256)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentListed(uint256,address,string,uint8)": TypedContractEvent<
      AgentListedEvent.InputTuple,
      AgentListedEvent.OutputTuple,
      AgentListedEvent.OutputObject
    >;
    AgentListed: TypedContractEvent<
      AgentListedEvent.InputTuple,
      AgentListedEvent.OutputTuple,
      AgentListedEvent.OutputObject
    >;

    "AgentRated(uint256,address,uint8)": TypedContractEvent<
      AgentRatedEvent.InputTuple,
      AgentRatedEvent.OutputTuple,
      AgentRatedEvent.OutputObject
    >;
    AgentRated: TypedContractEvent<
      AgentRatedEvent.InputTuple,
      AgentRatedEvent.OutputTuple,
      AgentRatedEvent.OutputObject
    >;

    "AgentRented(uint256,address,uint256,uint256)": TypedContractEvent<
      AgentRentedEvent.InputTuple,
      AgentRentedEvent.OutputTuple,
      AgentRentedEvent.OutputObject
    >;
    AgentRented: TypedContractEvent<
      AgentRentedEvent.InputTuple,
      AgentRentedEvent.OutputTuple,
      AgentRentedEvent.OutputObject
    >;

    "EarningsWithdrawn(address,uint256)": TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;
    EarningsWithdrawn: TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;

    "TaskExecuted(uint256,bytes32,address)": TypedContractEvent<
      TaskExecutedEvent.InputTuple,
      TaskExecutedEvent.OutputTuple,
      TaskExecutedEvent.OutputObject
    >;
    TaskExecuted: TypedContractEvent<
      TaskExecutedEvent.InputTuple,
      TaskExecutedEvent.OutputTuple,
      TaskExecutedEvent.OutputObject
    >;
  };
}
