/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AgentMarketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentMarketplace__factory>;
    getContractFactory(
      name: "IPersistentAgent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPersistentAgent__factory>;
    getContractFactory(
      name: "ISovereignAgent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISovereignAgent__factory>;
    getContractFactory(
      name: "RittyAgent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RittyAgent__factory>;
    getContractFactory(
      name: "RittyProfile",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RittyProfile__factory>;
    getContractFactory(
      name: "IStakingPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStakingPool__factory>;
    getContractFactory(
      name: "RittyRental",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RittyRental__factory>;
    getContractFactory(
      name: "IMarketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMarketplace__factory>;
    getContractFactory(
      name: "IRental",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRental__factory>;
    getContractFactory(
      name: "RittyStakingPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RittyStakingPool__factory>;

    getContractAt(
      name: "AgentMarketplace",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentMarketplace>;
    getContractAt(
      name: "IPersistentAgent",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPersistentAgent>;
    getContractAt(
      name: "ISovereignAgent",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISovereignAgent>;
    getContractAt(
      name: "RittyAgent",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RittyAgent>;
    getContractAt(
      name: "RittyProfile",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RittyProfile>;
    getContractAt(
      name: "IStakingPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IStakingPool>;
    getContractAt(
      name: "RittyRental",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RittyRental>;
    getContractAt(
      name: "IMarketplace",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMarketplace>;
    getContractAt(
      name: "IRental",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRental>;
    getContractAt(
      name: "RittyStakingPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RittyStakingPool>;

    deployContract(
      name: "AgentMarketplace",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentMarketplace>;
    deployContract(
      name: "IPersistentAgent",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPersistentAgent>;
    deployContract(
      name: "ISovereignAgent",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignAgent>;
    deployContract(
      name: "RittyAgent",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RittyAgent>;
    deployContract(
      name: "RittyProfile",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RittyProfile>;
    deployContract(
      name: "IStakingPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakingPool>;
    deployContract(
      name: "RittyRental",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RittyRental>;
    deployContract(
      name: "IMarketplace",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMarketplace>;
    deployContract(
      name: "IRental",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRental>;
    deployContract(
      name: "RittyStakingPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RittyStakingPool>;

    deployContract(
      name: "AgentMarketplace",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentMarketplace>;
    deployContract(
      name: "IPersistentAgent",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPersistentAgent>;
    deployContract(
      name: "ISovereignAgent",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignAgent>;
    deployContract(
      name: "RittyAgent",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RittyAgent>;
    deployContract(
      name: "RittyProfile",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RittyProfile>;
    deployContract(
      name: "IStakingPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakingPool>;
    deployContract(
      name: "RittyRental",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RittyRental>;
    deployContract(
      name: "IMarketplace",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMarketplace>;
    deployContract(
      name: "IRental",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRental>;
    deployContract(
      name: "RittyStakingPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RittyStakingPool>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
