/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace RittyAgent {
  export type ChatMessageStruct = {
    user: AddressLike;
    message: string;
    timestamp: BigNumberish;
    response: string;
  };

  export type ChatMessageStructOutput = [
    user: string,
    message: string,
    timestamp: bigint,
    response: string
  ] & { user: string; message: string; timestamp: bigint; response: string };
}

export interface RittyAgentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activate"
      | "category"
      | "chat"
      | "deactivate"
      | "getMessage"
      | "getMessageCount"
      | "isActive"
      | "messageIds"
      | "messages"
      | "name"
      | "onLlmResult"
      | "owner"
      | "systemPrompt"
      | "updateSystemPrompt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentActivated" | "ChatRequested" | "ChatResponse"
  ): EventFragment;

  encodeFunctionData(functionFragment: "activate", values?: undefined): string;
  encodeFunctionData(functionFragment: "category", values?: undefined): string;
  encodeFunctionData(functionFragment: "chat", values: [string]): string;
  encodeFunctionData(
    functionFragment: "deactivate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "messageIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "messages", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onLlmResult",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "systemPrompt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateSystemPrompt",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "activate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "category", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "chat", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deactivate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMessage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMessageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "messageIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "messages", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onLlmResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "systemPrompt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSystemPrompt",
    data: BytesLike
  ): Result;
}

export namespace AgentActivatedEvent {
  export type InputTuple = [name: string, category: string];
  export type OutputTuple = [name: string, category: string];
  export interface OutputObject {
    name: string;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChatRequestedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    user: AddressLike,
    message: string
  ];
  export type OutputTuple = [requestId: string, user: string, message: string];
  export interface OutputObject {
    requestId: string;
    user: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChatResponseEvent {
  export type InputTuple = [requestId: BytesLike, response: string];
  export type OutputTuple = [requestId: string, response: string];
  export interface OutputObject {
    requestId: string;
    response: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RittyAgent extends BaseContract {
  connect(runner?: ContractRunner | null): RittyAgent;
  waitForDeployment(): Promise<this>;

  interface: RittyAgentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activate: TypedContractMethod<[], [void], "nonpayable">;

  category: TypedContractMethod<[], [string], "view">;

  chat: TypedContractMethod<[userMessage: string], [string], "nonpayable">;

  deactivate: TypedContractMethod<[], [void], "nonpayable">;

  getMessage: TypedContractMethod<
    [requestId: BytesLike],
    [RittyAgent.ChatMessageStructOutput],
    "view"
  >;

  getMessageCount: TypedContractMethod<[], [bigint], "view">;

  isActive: TypedContractMethod<[], [boolean], "view">;

  messageIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  messages: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string] & {
        user: string;
        message: string;
        timestamp: bigint;
        response: string;
      }
    ],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  onLlmResult: TypedContractMethod<
    [requestId: BytesLike, result: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  systemPrompt: TypedContractMethod<[], [string], "view">;

  updateSystemPrompt: TypedContractMethod<
    [_newPrompt: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "category"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "chat"
  ): TypedContractMethod<[userMessage: string], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMessage"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [RittyAgent.ChatMessageStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMessageCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "messageIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "messages"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string] & {
        user: string;
        message: string;
        timestamp: bigint;
        response: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onLlmResult"
  ): TypedContractMethod<
    [requestId: BytesLike, result: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "systemPrompt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateSystemPrompt"
  ): TypedContractMethod<[_newPrompt: string], [void], "nonpayable">;

  getEvent(
    key: "AgentActivated"
  ): TypedContractEvent<
    AgentActivatedEvent.InputTuple,
    AgentActivatedEvent.OutputTuple,
    AgentActivatedEvent.OutputObject
  >;
  getEvent(
    key: "ChatRequested"
  ): TypedContractEvent<
    ChatRequestedEvent.InputTuple,
    ChatRequestedEvent.OutputTuple,
    ChatRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ChatResponse"
  ): TypedContractEvent<
    ChatResponseEvent.InputTuple,
    ChatResponseEvent.OutputTuple,
    ChatResponseEvent.OutputObject
  >;

  filters: {
    "AgentActivated(string,string)": TypedContractEvent<
      AgentActivatedEvent.InputTuple,
      AgentActivatedEvent.OutputTuple,
      AgentActivatedEvent.OutputObject
    >;
    AgentActivated: TypedContractEvent<
      AgentActivatedEvent.InputTuple,
      AgentActivatedEvent.OutputTuple,
      AgentActivatedEvent.OutputObject
    >;

    "ChatRequested(bytes32,address,string)": TypedContractEvent<
      ChatRequestedEvent.InputTuple,
      ChatRequestedEvent.OutputTuple,
      ChatRequestedEvent.OutputObject
    >;
    ChatRequested: TypedContractEvent<
      ChatRequestedEvent.InputTuple,
      ChatRequestedEvent.OutputTuple,
      ChatRequestedEvent.OutputObject
    >;

    "ChatResponse(bytes32,string)": TypedContractEvent<
      ChatResponseEvent.InputTuple,
      ChatResponseEvent.OutputTuple,
      ChatResponseEvent.OutputObject
    >;
    ChatResponse: TypedContractEvent<
      ChatResponseEvent.InputTuple,
      ChatResponseEvent.OutputTuple,
      ChatResponseEvent.OutputObject
    >;
  };
}
